package com.sorbonne.safetyline.model;

public class Connexion
{
    private String idUser;
    //Ticket generated by server
    private String id_ticket;

    public Connexion(String idUser, String id_ticket) {
        this.idUser = idUser;
        this.id_ticket = id_ticket;
    }

    private static int index = 0;

    public String getIdUser() {
        return idUser;
    }

    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    public String getId_ticket() {
        return id_ticket;
    }

    public void setId_ticket(String id_ticket) {
        this.id_ticket = id_ticket;
    }

    public static int getIndex() {
        return index;
    }

    public static void setIndex(int index) {
        Connexion.index = index;
    }
}
