package com.sorbonne.safetyline.model;
import javax.validation.constraints.*;
public class User
{

    @NotNull(message = "please enter an email")
    @NotBlank(message = "please enter an email")
    @Email( message = "Your email must have an email format")
    private String idUser;


    @NotNull( message = "Please enter a password")
    @NotBlank( message = "Your password must contain at least one character")
    @Size( max=30, min=6)
    private String password;


    @NotNull( message = "admin cannot be null")
    private boolean admin;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    private String name;

    private String firstName;

    //Ticket generated by server
    private String id_ticket;
    private static int index = 0;


    public User(String idUser, String password, Boolean adm)
    {
        super();
        this.id_ticket = String.valueOf(index++) ;
        this.idUser = idUser;
        this.password = password;
        this.admin = adm == null ? false : true;
    }


    public void setIndex(int id)
    {
        this.index = id;
    }

    public String getId_ticket() {
        return id_ticket;
    }

    public void setId_ticket(String id_ticket) {
        this.id_ticket = id_ticket;

    }
    public void setId_ticket(int id_ticket) {
        this.id_ticket = String.valueOf(id_ticket);
    }
    public boolean isAdmin() {
        return admin;
    }

    public void setAdmin(boolean admin) {
        this.admin = admin;
    }

    public String getIdUser() {
        return idUser;
    }

    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    public String toString()
    {
        String res = "";
        res += "idUser : "+this.idUser+" password :"+this.password + " is admin: "+this.isAdmin();
        return res;
    }
}
