version: '3'
services:
 db: 
  image: mysql
  restart: always
  container_name: db-mysql
  ports:
  - "4401:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_USER=user
  - MYSQL_PASSWORD=userpassword
  - MYSQL_DATABASE=safetyline
  volumes:
    - ./dump:/docker-entrypoint-initdb.d